In [1]:
import pickle
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
from scipy import special                 
import array
import scipy as sp
from scipy import spatial
from scipy.stats import binned_statistic

In [40]:
with open('a_lyman_limited_value.pkl', 'rb') as f:
    lyman = pickle.load(f)
lyman_distance = []
for i in lyman:
    for z in i:
        if(z[0] > 10**21):
            lyman_distance.append((np.log10(z[0]),z[4]))
lyman_distance.sort(key = lambda row:(row[0]))

In [47]:
len(lyman_distance)

53

In [25]:
def distance(points1, points2):
    return(np.sqrt((points1[0]-points2[0])**2 +(points1[1]-points2[1])**2+(points1[2]-points2[2])**2))

In [26]:
def no_galaxies(lyman_distance):    
    checkout = []
    gals = np.loadtxt('hpropsRS.res', usecols=[5,6,7,8],unpack=1) 
    points = []
    for i,j,k in zip(gals[0],gals[1],gals[2]):
        points.append([i,j,k])
    radius_points = []
    for i in gals[3]:
        radius_points.append(i)
    points.append([0,0,0])
    for i in lyman_distance:
        points[-1] = i[1]
        tree = spatial.KDTree(points)
        all_nn_indices = tree.query_ball_point(points[-1],r=2.175e-01)
        counts = 0
        for k in all_nn_indices:
                if(points[k] != points[-1]):
                    if(distance(i[1],points[k]) > radius_points[k]):
                        #if true 
                        counts +=1
                        if(counts == len(all_nn_indices)-1):
                            checkout.append([i[0],i[1]])
    return checkout

In [27]:
nogalaxies  = no_galaxies(lyman_distance)

In [39]:
with open('nogalaxies_associated_20+.pkl', 'wb') as f:
    pickle.dump(nogalaxies, f, protocol=pickle.HIGHEST_PROTOCOL)

In [36]:
gals = np.loadtxt('hpropsRS.res', usecols=[5,6,7,8],unpack=1) 
checkout = []
points = []
for i,j,k in zip(gals[0],gals[1],gals[2]):
    points.append([i,j,k])
    radius_points = []
radius_points = []
for i in gals[3]:
    radius_points.append(i)
size = []
for p in high_col:
    for i in range(len(points)):
        if(radius_points[i]*6 > distance(p[1],points[i])):
            checkout.append(points[i])
            size.append(radius_points[i])


In [45]:
difference  = []
for i in checkout:
    difference.append(np.subtract(i,high_col[-1][1]))
difference

[array([-22.6022557 , -15.4202307 ,  19.24810075]),
 array([-22.6682357 , -14.5867307 ,  19.33158075]),
 array([-22.7129957 , -14.6267207 ,  19.37459075]),
 array([-22.5510957 , -14.5679607 ,  19.31569075]),
 array([-22.6637857 , -14.6335607 ,  19.38373075]),
 array([-22.5230657 , -14.5391207 ,  19.31894075]),
 array([-22.5667357 , -14.5074107 ,  19.32904075]),
 array([-22.6388257 , -14.6198307 ,  19.29820075]),
 array([-22.6234657 , -14.5994707 ,  19.38055075]),
 array([-22.6084257 , -14.5852907 ,  19.31327075]),
 array([-22.6091557 , -14.4867507 ,  19.35763075]),
 array([-0.0078057 ,  0.0141093 , -0.16918925]),
 array([ 0.0317743 ,  0.0122393 , -0.00131925]),
 array([-0.0141057 , -0.0216807 , -0.05019925]),
 array([-0.0168457 , -0.0126507 ,  0.02161075])]