In [1]:
import pickle
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
from scipy import special                 
import array
import scipy as sp
from scipy import spatial
from scipy.stats import binned_statistic


In [2]:
weird_lls = [15.342845754022335, 5.714211262813436, 32.154595166400604]

In [3]:
#the two that should be looked at and find.
[0.0634495415999153, 0.04176, 21.018545955684957],
[0.08521943240295256, 0.03235, 21.018545955684957],

([0.08521943240295256, 0.03235, 21.018545955684957],)

In [9]:
def distance(points1, points2):
    return(np.sqrt((points1[0]-points2[0])**2 +(points1[1]-points2[1])**2+(points1[2]-points2[2])**2))

In [28]:
gals = np.loadtxt('hpropsRS.res', usecols=[5,6,7,8],unpack=1) 
checkout = []
points = []
for i,j,k in zip(gals[0],gals[1],gals[2]):
    points.append([i,j,k])
    radius_points = []
radius_points = []
for i in gals[3]:
    radius_points.append(i)
size = []
for i in range(len(points)):
    if(radius_points[i]*6 > distance(weird_lls,points[i])):
        checkout.append(points[i])
        size.append(radius_points[i])


In [29]:
size

[0.2175,
 0.04176,
 0.03245,
 0.03235,
 0.0245,
 0.02035,
 0.01932,
 0.0169,
 0.01458,
 0.01091,
 0.0107]

In [30]:
checkout

[[15.36895, 4.83146, 32.06794],
 [15.30297, 5.66496, 32.15142],
 [15.25821, 5.62497, 32.19443],
 [15.42011, 5.68373, 32.13553],
 [15.30742, 5.61813, 32.20357],
 [15.44814, 5.71257, 32.13878],
 [15.40447, 5.74428, 32.14888],
 [15.33238, 5.63186, 32.11804],
 [15.34774, 5.65222, 32.20039],
 [15.36278, 5.6664, 32.13311],
 [15.36205, 5.76494, 32.17747]]

In [31]:
difference  = []
for i in checkout:
    difference.append(np.subtract(i,weird_lls))

In [32]:
difference

[array([ 0.02610425, -0.88275126, -0.08665517]),
 array([-0.03987575, -0.04925126, -0.00317517]),
 array([-0.08463575, -0.08924126,  0.03983483]),
 array([ 0.07726425, -0.03048126, -0.01906517]),
 array([-0.03542575, -0.09608126,  0.04897483]),
 array([ 0.10529425, -0.00164126, -0.01581517]),
 array([ 0.06162425,  0.03006874, -0.00571517]),
 array([-0.01046575, -0.08235126, -0.03655517]),
 array([ 0.00489425, -0.06199126,  0.04579483]),
 array([ 0.01993425, -0.04781126, -0.02148517]),
 array([0.01920425, 0.05072874, 0.02287483])]